version: "3.2"

services:
  jira-service-desk:
    image: atlassian/jira-servicedesk
    container_name: jira-service-desk
    restart: always
    volumes:
      - jiradata:/var/atlassian/jira    
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=dummypassword
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      - JVM_MINIMUM_MEMORY=2048m
      - JVM_MAXIMUM_MEMORY=4096m      
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:9.5-alpine
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=dummypassword
      - POSTGRES_DB=jiradb
    ports:
     - "5432:5432"

volumes:
  jiradata:
  postgresqldata:

networks:
  default:
    external:
      name: jira-network